final List<String> categories = [
  'Estates',
  'Vehicles',
  'Fashion & Beauty',
  'Mobiles',
  'Furniturs',
  'Computers',
  'Gifts',
  'Babies stuff',
  'Motorcycles',
  'Sport',
  'Pharmacies',
  'Services',
  'Variants',
  'Malls',
];
